name: run
run_id: commands[0]
env COLUMNS: 147
env HOME: /Users/carlosurrego
env LANG: en_US.UTF-8
env LINES: 16
env PATH: /Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/bin:/Users/carlosurrego/Downloads/env-api/bin:/Users/carlosurrego/.nvm/versions/node/v20.15.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONHASHSEED: 1106104841
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env SSH_AUTH_SOCK: ***************************************************
env TERM: xterm-256color
env TMPDIR: /var/folders/5s/kf7ph7pd0w12ldc2vjrxpgjh0000gp/T/
env TOX_ENV_DIR: /Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app
env TOX_ENV_NAME: run
env TOX_WORK_DIR: /Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox
env VIRTUAL_ENV: /Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app
metadata pid: 58719
cwd: /Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos
allow: /Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/bin/*
cmd: python app/main.py
exit_code: -2
[32mINFO[0m:     127.0.0.1:52063 - "[1mOPTIONS /api/v1/predict HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:52063 - "[1mPOST /api/v1/predict HTTP/1.1[0m" [31m422 Unprocessable Entity[0m
[32mINFO[0m:     127.0.0.1:54099 - "[1mPOST /api/v1/predict HTTP/1.1[0m" [31m422 Unprocessable Entity[0m
[32mINFO[0m:     127.0.0.1:54318 - "[1mPOST /api/v1/predict HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:54442 - "[1mPOST /api/v1/predict HTTP/1.1[0m" [32m200 OK[0m

standard error:
[32m2025-09-19 10:34:56.845[0m | [33m[1mWARNING [0m | [36m__main__[0m:[36m<module>[0m:[36m55[0m - [33m[1mRunning in development mode. Do not run like this in production.[0m
[32mINFO[0m:     Started server process [[36m58719[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8001[0m (Press CTRL+C to quit)
[32m2025-09-19 10:45:15.945[0m | [1mINFO    [0m | [36mapp.api[0m:[36mpredict[0m:[36m38[0m - [1minput_data: inputs=['Sample text for prediction'][0m
[32m2025-09-19 10:45:15.946[0m | [1mINFO    [0m | [36mapp.api[0m:[36mpredict[0m:[36m39[0m - [1mMaking prediction on inputs: ['Sample text for prediction'][0m
[32m2025-09-19 10:45:15.946[0m | [1mINFO    [0m | [36mapp.api[0m:[36mpredict[0m:[36m47[0m - [1mPrediction results: [1][0m
[32m2025-09-19 10:45:37.976[0m | [1mINFO    [0m | [36mapp.api[0m:[36mpredict[0m:[36m38[0m - [1minput_data: inputs=['fdsfs'][0m
[32m2025-09-19 10:45:37.976[0m | [1mINFO    [0m | [36mapp.api[0m:[36mpredict[0m:[36m39[0m - [1mMaking prediction on inputs: ['fdsfs'][0m
[32m2025-09-19 10:45:37.976[0m | [1mINFO    [0m | [36mapp.api[0m:[36mpredict[0m:[36m47[0m - [1mPrediction results: [1][0m
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Finished server process [[36m58719[0m]
[31mERROR[0m:    Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/starlette/routing.py", line 701, in lifespan
    await receive()
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/app/main.py", line 59, in <module>
    uvicorn.run(app, host="0.0.0.0", port=8001, log_level="debug")
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/carlosurrego/Documents/master/desarrollo-soluciones/Clasificacion-de-textos-medicos/.tox/test_app/lib/python3.12/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "/opt/anaconda3/lib/python3.12/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
